name: Publish Docker images to Docker Hub
on: 
  push: 
    branches: [main]

jobs: 
  build_and_push:
    name: Build and push images to docker hub
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Increment version
        id: version
        run: ./increment_version.sh

      - name: Commit new version
        run: |
          git config --global user.name ${{secrets.USERNAME_GITHUB}}
          git config --global user.email ${{secrets.USEREMAIL_GITHUB}}
          git remote set-url origin https://${{secrets.USERNAME_GITHUB}}:${{ secrets.PAT }}@github.com/${{secrets.USERNAME_GITHUB}}/hello-world-cicd-pipeline-docker.git
          git add VERSION
          git commit -m "Increment version to ${{ steps.version.outputs.new_version }}"
          git push origin main

      - name: Docker meta data fields set ( tag, label)
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{ secrets.DOCKERHUB_USERNAME }}/react-hello-world
      
      - name: Build and push docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-hello-world:v${{ steps.version.outputs.new_version }}
          labels: ${{ steps.meta.outputs.labels}} 
      
#      - name: Deploy container
#       run: |
#        docker run -d -p 3002:3000 --name my-react-app ${{ secrets.DOCKERHUB_USERNAME }}/react-hello-world:latest
