name: Publish Docker images to Docker Hub
on: 
  push: 
    branches: [codeql]
  
jobs: 
  build_and_push:
    name: Build and push images to docker hub
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      # actions: read
      # contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: javascript-typescript
          build-mode: none

    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Increment version
        id: version
        run: |
          ./increment_version.sh
          cat VERSION
    
      - name: Commit updated VERSION file
        run: |
          git config --global user.name "pushpa-u"
          git config --global user.email "pushpa.u@10decoders.in"
          git add VERSION
          git commit -m "Increment version to ${{ steps.version.outputs.new_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} 

      - name: Docker meta data fields set ( tag, label)
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{ secrets.DOCKERHUB_USERNAME }}/react-dokcer-pipeline
      
      - name: Build and push docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-dokcer-pipeline:v${{ steps.version.outputs.new_version }}
          labels: ${{ steps.meta.outputs.labels}} 
      
